# Generated by Django 4.1.2 on 2022-10-20 15:01

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default=api.models.uuid4, editable=False, max_length=33, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.CharField(default=api.models.uuid4, editable=False, max_length=33, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=api.models.uuid4, editable=False, max_length=33, primary_key=True, serialize=False, unique=True),
        ),
    ]
